defaults:
  - set: train

base_dir: /perm/mafp/s2s-links/splitter-output
base_dir_read_only: /perm/mafp/s2s-links/read-only


fields:
  u: 
    - 200
    - 850
  v:
    - 200
    - 850
  gh:
    - 1000
    - 500
    - 200
center: 'ecmwf'
n_workers: ${oc.env:SLURM_CPUS_PER_TASK,4}
overwrite: False